import type {Metadata} from "next";
import {Roboto} from "next/font/google";
import "./globals.css";

const inter = Roboto({subsets: ["latin"], weight: ["400", "500", "700"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function LocaleLayout({
                                         children,
                                         params: {locale}
                                     }: {
    children: React.ReactNode;
    params: { locale: string };
}) {
    return (
        <html lang={locale}>
        <body>{children}</body>
        </html>
    );
}
